//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Account.java
//  @ Date : 7/18/2014
//  @ Author : 
//
//
package AtmGeneratedCode;

public class Account
{
    private int accountNumber;
    private int pin;
    private double availableBalance;
    private double totalBalance;

    public Account(int accountNumber, int pin, double availableBalance,
            double totalBalance)
    {
        super();
        this.accountNumber = accountNumber;
        this.pin = pin;
        this.availableBalance = availableBalance;
        this.totalBalance = totalBalance;
    }

    public boolean validatePin(int userPin)
    {
        return (userPin == pin);
    }

    public double getAvailableBalance()
    {
        return availableBalance;
    }

    public double getTotalBalance()
    {
        return totalBalance;
    }

    public void debit(double amount)
    {
        totalBalance -= amount;
        availableBalance -= amount;
    }

    public void credit(double amount)
    {
        totalBalance += amount;
    }

    public int getAccountNumber()
    {
        return accountNumber;
    }

}
