//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BalanceInquiry.java
//  @ Date : 7/18/2014
//  @ Author : 
//
//
package AtmGeneratedCode;

public class BalanceInquiry extends Transaction
{
    public BalanceInquiry(int accountNumber, Screen screen,
            BankDatabase bankDatabase)
    {
        super(accountNumber, screen, bankDatabase);
        // TODO Auto-generated constructor stub
    }

    @Override
    public void execute()
    {
        BankDatabase bankDatabase = super.getBankDatabase();
        Screen screen = super.getScreen();
        
        double availableBalance = bankDatabase.getAvailableBalance(getAccountNumber());
        double totalBalance = bankDatabase.getTotalBalance(getAccountNumber());
        
        screen.displayMessageLine("Balance information: ");
        screen.displayMessage(" - Available balance: ");
        screen.displayDollarAmount(availableBalance);
        screen.displayMessage("\n - Total balance: ");
        screen.displayDollarAmount(totalBalance);
        screen.displayMessageLine("");
    }
}
