//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BankDatabase.java
//  @ Date : 7/18/2014
//  @ Author : 
//
//
package AtmGeneratedCode;

public class BankDatabase
{
    private Account[] accounts;

    public BankDatabase()
    {
        accounts = new Account[2]; // just 2 accounts for testing
        accounts[0] = new Account(12345, 54321, 1000.0, 1200.0);
        accounts[1] = new Account(98765, 56789, 200.0, 200.0);
    }

    private Account getAccount(int accountNumber)
    {
        for (Account currentAccount : accounts)
        {
            if(currentAccount.getAccountNumber() == accountNumber)
            {
                return currentAccount;
            }
        }
        return null;
    }

    public boolean authenticateUser(int userAccountNumber, int userPin)
    {
        Account userAcount = getAccount(userAccountNumber);
        
        if (userAcount != null)
        {
            return userAcount.validatePin(userPin);
        }
        else
        {
            return false;
        }
    }

    public double getAvailableBalance(int userAccountNumber)
    {
        Account account = getAccount(userAccountNumber);
        return  account != null ? account.getAvailableBalance() : 0f;
    }

    public double getTotalBalance(int userAccountNumber)
    {
        Account account = getAccount(userAccountNumber);
        return  account != null ? account.getTotalBalance() : 0f;
    }

    public void credit(int userAccountNumber, double amount)
    {
        Account account = getAccount(userAccountNumber);
        if (account != null)
        {
            account.credit(amount);
        }
    }

    public void debit(int userAccountNumber, double amount)
    {
        Account account = getAccount(userAccountNumber);
        if (account != null)
        {
            account.debit(amount);
        }
    }
}
