//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DepositSlot.java
//  @ Date : 7/18/2014
//  @ Author : 
//
//
package AtmGeneratedCode;

public class DepositSlot
{
    public boolean isEnvelopeReceived()
    {
        // Indicates whether envelope was received (always returns true,
        // because this is only a software simulation of a real deposit slot)
        return true;
    }
}
