//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Screen.java
//  @ Date : 7/18/2014
//  @ Author : 
//
//
package AtmGeneratedCode;

/**
 * Represents the screen of the ATM and encapsulates all aspects of displaying
 * output to the user. Approximates a real ATM’s screen with a computer monitor
 * and outputs text messages using standard console output methods
 * 
 * @author nduy
 * 
 */
public class Screen
{
    public void displayMessageLine(String message)
    {
        System.out.println(message);
    }

    // Display message without a carriage return
    public void displayMessage(String message)
    {
        System.out.print(message);
    }
    
    public void displayDollarAmount(double amount)
    {
        System.out.printf("$%,2f", amount);
    }
}
